language: node_js
node_js:
  - 10
before_install:
  cd ./src/game-mapper/src
install:
  npm install
script:
  - npm run lint
  - npm run test-cover
  - npm run build
after_success:
  - bash <(curl -s https://codecov.io/bash)
